name = "raco-bot"
type = "webpack"
account_id = ""
workers_dev = false
route = "raco-bot.example.com/*"
zone_id = ""
webpack_config = "webpack.config.js"
kv_namespaces = [
    { binding = "KV", id = "" }
]

[vars]
TELEGRAM_BOT_USER_ID = ""
TELEGRAM_BOT_WEBHOOK_PATH = "bot"
FIBAPI_REDIRECT_URI = "https://raco-bot.example.com/oauth"
FIBAPI_OAUTH_CLIENT_ID = ""

[triggers]
# BE CAREFUL with the cron expressions
crons = ["*/15 7-23 * * 2-6"]  # runs every 15 minutes during 07:00-23:00 on every weekday
