name: Go

on:
  push:
    branches:
      - main
      - dev*
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/*.yml'
  pull_request:
    branches:
      - main
      - dev*
    types: [ opened, synchronize, reopened ]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/*.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

      - name: Get project dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
